name = "testing-d1-app-with-types"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "d1-app"
database_id = "your-database-id"
migrations_dir = "drizzle/migrations"
